In [99]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

In [100]:
df = pd.read_csv("Crop_recommendationnn.csv")
df.head()

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [101]:
df.shape

(2200, 8)

In [102]:
df.describe()

N            P            K  temperature     humidity  \
count  2200.000000  2200.000000  2200.000000  2200.000000  2200.000000   
mean     50.551818    53.362727    48.149091    25.616244    71.481779   
std      36.917334    32.985883    50.647931     5.063749    22.263812   
min       0.000000     5.000000     5.000000     8.825675    14.258040   
25%      21.000000    28.000000    20.000000    22.769375    60.261953   
50%      37.000000    51.000000    32.000000    25.598693    80.473146   
75%      84.250000    68.000000    49.000000    28.561654    89.948771   
max     140.000000   145.000000   205.000000    43.675493    99.981876   

                ph     rainfall  
count  2200.000000  2200.000000  
mean      6.469480   103.463655  
std       0.773938    54.958389  
min       3.504752    20.211267  
25%       5.971693    64.551686  
50%       6.425045    94.867624  
75%       6.923643   124.267508  
max       9.935091   298.560117

In [103]:
df["label"].value_counts()
list(df['label'].unique())

['rice',
 'maize',
 'chickpea',
 'kidneybeans',
 'pigeonpeas',
 'mothbeans',
 'mungbean',
 'blackgram',
 'lentil',
 'pomegranate',
 'banana',
 'mango',
 'grapes',
 'watermelon',
 'muskmelon',
 'apple',
 'orange',
 'papaya',
 'coconut',
 'cotton',
 'jute',
 'coffee']

In [38]:
df.groupby("label").mean()

N       P       K  temperature   humidity        ph  \
label                                                                   
apple         20.80  134.22  199.89    22.630942  92.333383  5.929663   
banana       100.23   82.01   50.05    27.376798  80.358123  5.983893   
blackgram     40.02   67.47   19.24    29.973340  65.118426  7.133952   
chickpea      40.09   67.79   79.92    18.872847  16.860439  7.336957   
coconut       21.98   16.93   30.59    27.409892  94.844272  5.976562   
coffee       101.20   28.74   29.94    25.540477  58.869846  6.790308   
cotton       117.77   46.24   19.56    23.988958  79.843474  6.912675   
grapes        23.18  132.53  200.11    23.849575  81.875228  6.025937   
jute          78.40   46.86   39.99    24.958376  79.639864  6.732778   
kidneybeans   20.75   67.54   20.05    20.115085  21.605357  5.749411   
lentil        18.77   68.36   19.41    24.509052  64.804785  6.927932   
maize         77.76   48.44   19.79    22.389204  65.092249  6.245190   
mango         20.07   27.18   29.92    31.208770  50.156573  5.766373   
mothbeans     21.44   48.01   20.23    28.194920  53.160418  6.831174   
mungbean      20.99   47.28   19.87    28.525775  85.499975  6.723957   
muskmelon    100.32   17.72   50.08    28.663066  92.342802  6.358805   
orange        19.58   16.55   10.01    22.765725  92.170209  7.016957   
papaya        49.88   59.05   50.04    33.723859  92.403388  6.741442   
pigeonpeas    20.73   67.73   20.29    27.741762  48.061633  5.794175   
pomegranate   18.87   18.75   40.21    21.837842  90.125504  6.429172   
rice          79.89   47.58   39.87    23.689332  82.272822  6.425471   
watermelon    99.42   17.00   50.22    25.591767  85.160375  6.495778   

               rainfall  
label                    
apple        112.654779  
banana       104.626980  
blackgram     67.884151  
chickpea      80.058977  
coconut      175.686646  
coffee       158.066295  
cotton        80.398043  
grapes        69.611829  
jute         174.792798  
kidneybeans  105.919778  
lentil        45.680454  
maize         84.766988  
mango         94.704515  
mothbeans     51.198487  
mungbean      48.403601  
muskmelon     24.689952  
orange       110.474969  
papaya       142.627839  
pigeonpeas   149.457564  
pomegranate  107.528442  
rice         236.181114  
watermelon    50.786219

In [90]:
# Separating the data and labels
x = df.drop(columns="label", axis=1)
y = df["label"]
x.columns.values

array(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall'],
      dtype=object)

## Data preprocessing

In [40]:
scaler = MinMaxScaler()

In [41]:
scaler.fit(x)

MinMaxScaler()

In [42]:
scaled_x = scaler.transform(x)

In [44]:
scaled_x

array([[0.64285714, 0.26428571, 0.19      , ..., 0.79026683, 0.46626364,
        0.65645778],
       [0.60714286, 0.37857143, 0.18      , ..., 0.77063285, 0.54948026,
        0.74167459],
       [0.42857143, 0.35714286, 0.195     , ..., 0.79397664, 0.67421877,
        0.87571039],
       ...,
       [0.84285714, 0.2       , 0.125     , ..., 0.61788046, 0.44443315,
        0.55007079],
       [0.83571429, 0.19285714, 0.145     , ..., 0.44175991, 0.50604494,
        0.38428046],
       [0.74285714, 0.09285714, 0.125     , ..., 0.53822177, 0.50931694,
        0.43372112]])

In [96]:
encoder = LabelEncoder()
df["label"] = encoder.fit_transform(df["label"])
print(encoder.classes_)
df.head()

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]


N   P   K  temperature   humidity        ph    rainfall  label
0  90  42  43    20.879744  82.002744  6.502985  202.935536     20
1  85  58  41    21.770462  80.319644  7.038096  226.655537     20
2  60  55  44    23.004459  82.320763  7.840207  263.964248     20
3  74  35  40    26.491096  80.158363  6.980401  242.864034     20
4  78  42  42    20.130175  81.604873  7.628473  262.717340     20

In [47]:
x = scaled_x
y = df["label"]

## Train test split

In [48]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y, test_size = .2, stratify = y, random_state = 1)

In [49]:
print(x.shape, xtrain.shape, xtest.shape)

(2200, 7) (1760, 7) (440, 7)


## Model Training

In [50]:
svm_model = SVC()
nb_model = GaussianNB()
rf_model = RandomForestClassifier(random_state=1)
svm_model.fit(xtrain, ytrain)
nb_model.fit(xtrain,ytrain)
rf_model.fit(xtrain,ytrain)

RandomForestClassifier(random_state=1)

In [53]:
svm_preds = svm_model.predict(xtrain)
nb_preds = nb_model.predict(xtrain)
rf_preds = rf_model.predict(xtrain)
rf_preds

array([ 7, 10,  8, ...,  4,  0, 15], dtype=int64)

In [65]:
from statistics import mode
final_preds = [mode([i,j,k]) for i,j,k in zip(svm_preds, nb_preds, rf_preds)]
final_preds

[7,
 10,
 8,
 20,
 2,
 10,
 1,
 21,
 0,
 5,
 3,
 17,
 12,
 8,
 9,
 21,
 15,
 7,
 6,
 19,
 17,
 17,
 15,
 16,
 6,
 1,
 6,
 17,
 4,
 19,
 1,
 21,
 4,
 12,
 19,
 4,
 2,
 21,
 9,
 14,
 15,
 21,
 16,
 10,
 17,
 8,
 21,
 12,
 16,
 14,
 12,
 9,
 0,
 21,
 2,
 1,
 1,
 19,
 11,
 10,
 9,
 3,
 17,
 14,
 5,
 4,
 19,
 21,
 16,
 8,
 4,
 21,
 9,
 4,
 16,
 5,
 0,
 6,
 10,
 10,
 14,
 16,
 0,
 4,
 6,
 12,
 17,
 14,
 19,
 5,
 7,
 12,
 6,
 6,
 20,
 7,
 8,
 8,
 15,
 15,
 9,
 21,
 2,
 12,
 7,
 7,
 20,
 16,
 10,
 7,
 19,
 10,
 3,
 13,
 18,
 3,
 5,
 21,
 5,
 6,
 9,
 0,
 10,
 12,
 14,
 20,
 9,
 1,
 17,
 5,
 20,
 3,
 6,
 6,
 20,
 8,
 7,
 7,
 20,
 18,
 9,
 2,
 4,
 6,
 9,
 13,
 8,
 11,
 14,
 4,
 8,
 1,
 7,
 3,
 11,
 8,
 8,
 16,
 5,
 12,
 1,
 1,
 9,
 15,
 6,
 8,
 4,
 6,
 19,
 19,
 7,
 14,
 9,
 9,
 5,
 8,
 10,
 4,
 21,
 9,
 8,
 13,
 15,
 9,
 7,
 19,
 7,
 15,
 2,
 21,
 8,
 11,
 0,
 16,
 8,
 8,
 18,
 6,
 21,
 6,
 1,
 14,
 11,
 18,
 2,
 10,
 2,
 20,
 16,
 20,
 1,
 5,
 6,
 7,
 3,
 11,
 15,
 9,
 19,
 3,
 17,
 13,
 14,
 1

In [66]:
# Accuracy score on training data
training_data_accuracy = accuracy_score(svm_preds,ytrain)
training_data_accuracy

0.9835227272727273

In [67]:
# Accuracy score on training data
training_data_accuracy = accuracy_score(nb_preds,ytrain)
training_data_accuracy

0.9948863636363636

In [68]:
# Accuracy score on training data
training_data_accuracy = accuracy_score(rf_preds,ytrain)
training_data_accuracy

1.0

In [69]:
# Accuracy score on training data
training_data_accuracy = accuracy_score(final_preds,ytrain)
training_data_accuracy

0.9948863636363636

In [71]:
# test data prediction
svm_preds = svm_model.predict(xtest)
nb_preds = nb_model.predict(xtest)
rf_preds = rf_model.predict(xtest)

In [77]:
final_preds = [mode([i,j,k]) for i,j,k in zip(svm_preds, nb_preds, rf_preds)]
final_preds

[20,
 19,
 6,
 19,
 7,
 9,
 15,
 0,
 20,
 4,
 4,
 19,
 15,
 3,
 13,
 14,
 20,
 14,
 17,
 20,
 2,
 12,
 14,
 19,
 1,
 4,
 2,
 18,
 7,
 17,
 8,
 3,
 18,
 18,
 18,
 4,
 0,
 7,
 21,
 16,
 0,
 17,
 19,
 16,
 6,
 15,
 21,
 2,
 12,
 9,
 6,
 7,
 4,
 3,
 6,
 12,
 17,
 4,
 1,
 11,
 8,
 19,
 3,
 4,
 13,
 0,
 6,
 10,
 10,
 13,
 0,
 17,
 13,
 18,
 14,
 14,
 11,
 0,
 6,
 21,
 6,
 3,
 15,
 15,
 10,
 8,
 18,
 18,
 11,
 0,
 5,
 3,
 10,
 13,
 10,
 13,
 20,
 17,
 2,
 4,
 7,
 3,
 12,
 7,
 20,
 21,
 6,
 20,
 20,
 16,
 8,
 3,
 14,
 14,
 12,
 3,
 7,
 13,
 18,
 14,
 4,
 12,
 14,
 7,
 16,
 9,
 5,
 21,
 8,
 2,
 8,
 16,
 13,
 16,
 5,
 1,
 17,
 13,
 0,
 2,
 1,
 7,
 13,
 12,
 4,
 9,
 9,
 18,
 0,
 15,
 15,
 18,
 12,
 8,
 17,
 17,
 6,
 4,
 13,
 20,
 14,
 16,
 11,
 1,
 10,
 2,
 11,
 8,
 17,
 1,
 1,
 21,
 1,
 16,
 4,
 17,
 6,
 11,
 11,
 15,
 10,
 12,
 10,
 11,
 4,
 1,
 2,
 15,
 20,
 8,
 21,
 2,
 4,
 9,
 17,
 3,
 10,
 19,
 21,
 1,
 21,
 2,
 7,
 3,
 6,
 10,
 6,
 6,
 5,
 19,
 7,
 19,
 12,
 12,
 19,
 2,
 16,
 20,
 11,
 16

In [78]:
training_data_accuracy = accuracy_score(svm_preds,ytest)
training_data_accuracy

0.990909090909091

In [79]:
training_data_accuracy = accuracy_score(nb_preds,ytest)
training_data_accuracy

0.9954545454545455

In [80]:
training_data_accuracy = accuracy_score(rf_preds,ytest)
training_data_accuracy

0.9977272727272727

In [81]:
training_data_accuracy = accuracy_score(final_preds,ytest)
training_data_accuracy

0.9977272727272727

## prediction system

In [88]:
# input_data=(90,42,43,20.87974371,82.00274423,6.502985292,202.9355362)  #rice
input_data = (71,54,16,22.61359953,63.69070564,5.749914421,87.75953857)  #maize

# changing the input to numpy array
input_data_as_nparray = np.asarray(input_data)

# reshaping the array
input_data_reshaped =input_data_as_nparray.reshape(1,-1)

#standardized the input data 
std_data = scaler.transform(input_data_reshaped)

print(std_data)

svm_prediction = svm_model.predict(std_data)
nb_prediction = nb_model.predict(std_data)
rf_prediction = rf_model.predict(std_data)

final_prediction = [mode([i,j,k]) for i,j,k in zip(svm_prediction, nb_prediction, rf_prediction)]
final_prediction


[[0.50714286 0.35       0.055      0.39563835 0.57665018 0.34915147
  0.24267487]]


c:\python38\lib\site-packages\sklearn\base.py:445: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


[11]

In [108]:
dict = {20: 'rice', 11: 'maize', 3: 'chickpea', 9: 'kidneybeans', 18: 'pigeonpeas', 13: 'mothbeans', 14: 'mungbean', 2: 'blackgram', 10: 'lentil', 19: 'pomegranate', 1: 'banana', 12: 'mango', 7: 'grapes', 21: 'watermelon', 15: 'muskmelon', 0: 'apple', 16: 'orange', 17: 'papaya', 4: 'coconut', 6: 'cotton', 8: 'jute', 5: 'coffee'}
dict[final_prediction[0]]

'maize'